/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

package projet;


import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Munoz and Porret
 */

public class Choisir_fichier extends javax.swing.JFrame {
    
    
    private Fichier fichier;
    private Interface_principale interface_accueil;
    
    public Choisir_fichier(Interface_principale interface_accueil) {
        this.interface_accueil = interface_accueil;
        this.setTitle("File Selection");
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/download-cloud3.png")).getImage()); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RAID Web - Choix du fichier");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                windowclosed(evt);
            }
        });

        jFileChooser1.setApproveButtonText("Sélectionner");
        jFileChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\"));
            jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jFileChooser1ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents
    
    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        //Cas où l'utlisateur clique sur le bouton "Sélectionner"
        if(evt.getActionCommand()=="ApproveSelection")
        {
            //On récupère le chemin absolu, le nom, la taille et l'icone du fichier
            String chemin= jFileChooser1.getSelectedFile().getAbsolutePath();
            String nom=jFileChooser1.getSelectedFile().getName();
            Icon icone=jFileChooser1.getIcon(jFileChooser1.getSelectedFile());
            Long taillefich=jFileChooser1.getSelectedFile().length();
            
            /*Création d'un objet de la classe Fichier permettant le stockage de 
            variables nécessaires pour la suite */ 
            fichier=new Fichier(chemin, nom, icone, taillefich);
            //Fermerture de la fenêtre de sélection du fichier
            dispose();
            /*Appel de la méthode permettant l'affichage graphique du fichier 
            sélectionné*/  
            interface_accueil.setFichier(fichier);
            
        }
        //Cas où l'utilisateur clique sur le bouton "Annuler"
        else if(evt.getActionCommand()=="CancelSelection")
        {
            //Fermeture de la fenêtre de sélection du fichier
            dispose();
            //On remet la fenêtre principale en premier plan
            interface_accueil.setAlwaysOnTop(true);
            interface_accueil.setEnabled(true);
            interface_accueil.setAlwaysOnTop(false);
        }
        
        
        
        
        
    }//GEN-LAST:event_jFileChooser1ActionPerformed
     // Cas où l'utilisateur clique sur le bouton "Fermer" de la fenêtre 
    private void windowclosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowclosed
        //On remet la fenêtre principale en premier plan
        interface_accueil.setAlwaysOnTop(true);
        interface_accueil.setEnabled(true);
        interface_accueil.setAlwaysOnTop(false);
    }//GEN-LAST:event_windowclosed
    
    
    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
